import {
  Megaphone,
  Presentation,
  Palette,
  Share2,
  PanelTop,
  Instagram,
  Linkedin,
  Rocket,
  Sparkles,
  Smartphone,
  TrendingUp,
  Handshake,
  Building2,
  PackageOpen,
  PenTool,
  RefreshCw,
  ShoppingBag,
  Monitor,
  CalendarDays,
  FileVideo,
} from 'lucide-react'
import type { TemplateCategory } from '../_types/dashboard-types'

// Template categories and sub-options based on service offerings
export const TEMPLATE_CATEGORIES: Record<string, TemplateCategory> = {
  'Launch Videos': {
    icon: Megaphone,
    categoryKey: 'launch-videos',
    description: 'Product videos that convert',
    modalDescription: 'Pick a format and tell us about your product.',
    options: [
      {
        title: 'Product Launch Video',
        optionKey: 'product-launch-video',
        description: 'Cinematic 30-60s reveal that builds hype around your launch.',
        prompt: 'Create a product launch video',
        icon: Rocket,
      },
      {
        title: 'Feature Explainer',
        optionKey: 'feature-highlight',
        description: 'Focused deep-dive that shows why one feature matters.',
        prompt: 'Create a feature explainer video',
        icon: Sparkles,
      },
      {
        title: 'App Walkthrough',
        optionKey: 'app-walkthrough',
        description: 'Guided screen-by-screen tour that onboards new users fast.',
        prompt: 'Create an app walkthrough video',
        icon: Smartphone,
      },
    ],
  },
  'Pitch Deck': {
    icon: Presentation,
    categoryKey: 'pitch-deck',
    description: 'Investor-ready presentations',
    modalDescription: 'Pick a deck type and share your key talking points.',
    options: [
      {
        title: 'Investor Pitch Deck',
        optionKey: 'investor-pitch-deck',
        description: '10-15 slides that make investors want to write a check.',
        prompt: 'Redesign my investor pitch deck',
        icon: TrendingUp,
      },
      {
        title: 'Sales Deck',
        optionKey: 'sales-deck',
        description: 'Slides that lead prospects straight to yes.',
        prompt: 'Create a sales presentation deck',
        icon: Handshake,
      },
      {
        title: 'Company Overview',
        optionKey: 'company-overview',
        description: 'A clear snapshot of who you are and what you do.',
        prompt: 'Design a company overview presentation',
        icon: Building2,
      },
    ],
  },
  Branding: {
    icon: Palette,
    categoryKey: 'branding',
    description: 'Complete visual identity',
    modalDescription: 'Tell us about your brand personality and audience.',
    options: [
      {
        title: 'Full Brand Package',
        optionKey: 'full-brand-package',
        description: 'Logo, colors, type, and guidelines — everything to launch.',
        prompt: 'Create a full brand package with logo and visual identity',
        icon: PackageOpen,
      },
      {
        title: 'Logo Design',
        optionKey: 'logo-design',
        description: 'Primary mark, wordmark, and icon variations.',
        prompt: 'Design a logo for my brand',
        icon: PenTool,
      },
      {
        title: 'Brand Refresh',
        optionKey: 'brand-refresh',
        description: 'Modernize your look without losing what people recognize.',
        prompt: 'Refresh and modernize my existing brand',
        icon: RefreshCw,
      },
    ],
  },
  'Social Media': {
    icon: Share2,
    categoryKey: 'social-media',
    description: 'Ads, content & video edits',
    modalDescription: 'Pick a content type and platform.',
    options: [
      {
        title: 'Instagram Post',
        optionKey: 'instagram-post',
        description: 'Scroll-stopping static posts optimized for the feed.',
        prompt: 'Create Instagram post designs',
        icon: Instagram,
      },
      {
        title: 'Instagram Story',
        optionKey: 'instagram-story',
        description: 'Vertical Stories that drive taps and replies.',
        prompt: 'Create Instagram story designs',
        icon: Instagram,
      },
      {
        title: 'Instagram Reels',
        optionKey: 'instagram-reels',
        description: 'Short-form vertical video that hooks in the first second.',
        prompt: 'Create an Instagram Reels video',
        icon: FileVideo,
      },
      {
        title: 'LinkedIn Content',
        optionKey: 'linkedin-content',
        description: 'Professional carousels and visual posts.',
        prompt: 'Create LinkedIn content',
        icon: Linkedin,
      },
      {
        title: 'Video Edit',
        optionKey: 'video-edit',
        description: 'Raw footage in, polished content out.',
        prompt: 'Edit my video footage for social media',
        icon: FileVideo,
      },
      {
        title: 'Ad Creatives',
        optionKey: 'ad-creatives',
        description: 'Scroll-stopping ads with A/B variants built in.',
        prompt: 'Create social media ad creatives',
        icon: Megaphone,
      },
    ],
  },
  'Content Calendar': {
    icon: CalendarDays,
    categoryKey: 'content-calendar',
    description: 'Strategic content planning',
    modalDescription: "Pick a planning scope and we'll map out your cadence.",
    options: [
      {
        title: 'Social Media Calendar',
        optionKey: 'social-media-calendar',
        description: 'A structured weekly posting plan you can actually stick to.',
        prompt: 'Create a social media content calendar',
        icon: Share2,
      },
      {
        title: 'Multi-Platform Campaign',
        optionKey: 'multi-platform-campaign',
        description: 'One message, every platform, perfectly coordinated.',
        prompt: 'Plan a multi-platform content campaign',
        icon: Megaphone,
      },
      {
        title: 'Launch Content Plan',
        optionKey: 'launch-content-plan',
        description: 'Build hype before launch, keep momentum after.',
        prompt: 'Create a product launch content plan',
        icon: Rocket,
      },
    ],
  },
  'Landing Page': {
    icon: PanelTop,
    categoryKey: 'landing-page',
    description: 'High-converting web pages',
    modalDescription: 'Pick a page type and describe your product or campaign.',
    options: [
      {
        title: 'Product Landing Page',
        optionKey: 'product-landing-page',
        description: 'One page, one action, maximum conversions.',
        prompt: 'Design a product landing page',
        icon: ShoppingBag,
      },
      {
        title: 'SaaS Landing Page',
        optionKey: 'saas-landing-page',
        description: 'Turn free users into paying customers.',
        prompt: 'Design a SaaS landing page',
        icon: Monitor,
      },
      {
        title: 'Event Landing Page',
        optionKey: 'event-landing-page',
        description: 'Build urgency and capture sign-ups.',
        prompt: 'Design an event landing page',
        icon: CalendarDays,
      },
    ],
  },
}
