/**
 * Industry and style keyword constants for chat context extraction
 */

/** Keywords mapped by industry for detecting industry from conversation messages */
export const INDUSTRY_KEYWORDS: Record<string, string[]> = {
  food_beverage: [
    'coffee',
    'cafe',
    'restaurant',
    'bakery',
    'food',
    'drinks',
    'menu',
    'recipe',
    'catering',
    'bar',
    'kitchen',
    'chef',
    'brew',
    'roast',
    'dining',
  ],
  fitness: [
    'gym',
    'fitness',
    'workout',
    'exercise',
    'yoga',
    'wellness',
    'training',
    'athletic',
    'sports',
    'running',
    'crossfit',
  ],
  technology: [
    'tech',
    'software',
    'app',
    'saas',
    'ai',
    'api',
    'platform',
    'startup',
    'developer',
    'engineering',
    'data',
    'cloud',
    'machine learning',
  ],
  finance: [
    'bank',
    'finance',
    'fintech',
    'investment',
    'insurance',
    'payment',
    'crypto',
    'trading',
    'accounting',
  ],
  fashion: [
    'fashion',
    'clothing',
    'apparel',
    'boutique',
    'style',
    'designer',
    'wear',
    'outfit',
    'accessories',
  ],
  beauty: ['beauty', 'skincare', 'cosmetics', 'spa', 'salon', 'makeup', 'skin', 'hair', 'nails'],
  real_estate: [
    'real estate',
    'property',
    'home',
    'apartment',
    'rental',
    'house',
    'realtor',
    'housing',
  ],
  education: [
    'education',
    'course',
    'learning',
    'school',
    'university',
    'teach',
    'tutor',
    'academy',
    'training',
  ],
  healthcare: [
    'health',
    'medical',
    'clinic',
    'doctor',
    'patient',
    'care',
    'hospital',
    'therapy',
    'dental',
  ],
  entertainment: [
    'entertainment',
    'music',
    'gaming',
    'movie',
    'film',
    'video',
    'streaming',
    'podcast',
  ],
  retail: ['retail', 'shop', 'store', 'ecommerce', 'shopping', 'product', 'merchandise'],
  luxury: ['luxury', 'premium', 'exclusive', 'high-end', 'upscale', 'boutique', 'designer'],
}

/** Industry-related keywords for context extraction */
export const CONTEXT_INDUSTRY_KEYWORDS = [
  'tech',
  'technology',
  'ai',
  'artificial intelligence',
  'machine learning',
  'ml',
  'fitness',
  'health',
  'wellness',
  'finance',
  'fintech',
  'crypto',
  'blockchain',
  'food',
  'restaurant',
  'retail',
  'ecommerce',
  'fashion',
  'beauty',
  'travel',
  'education',
  'gaming',
  'entertainment',
  'music',
  'sports',
  'automotive',
  'real estate',
  'healthcare',
  'saas',
  'startup',
  'b2b',
  'b2c',
  'luxury',
  'developer',
  'developers',
  'api',
  'software',
  'engineering',
  'data',
  'cloud',
]

/** Visual style keywords for context extraction */
export const CONTEXT_STYLE_KEYWORDS = [
  'minimal',
  'minimalist',
  'bold',
  'vibrant',
  'colorful',
  'elegant',
  'premium',
  'playful',
  'fun',
  'professional',
  'corporate',
  'modern',
  'classic',
  'vintage',
  'retro',
  'clean',
  'simple',
  'complex',
  'detailed',
  'sleek',
  'fresh',
  'dynamic',
  'energetic',
  'calm',
  'serene',
  'sophisticated',
  'luxurious',
  'organic',
  'natural',
]
