export interface WebsiteInspirationSeedData {
  name: string
  url: string
  industry: string[]
  styleTags: string[]
  colorSamples: string[]
  sectionTypes: string[]
  typography: string | null
  layoutStyle: string | null
  description: string
  displayOrder: number
}

export const WEBSITE_INSPIRATIONS_DATA: WebsiteInspirationSeedData[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // LAW FIRM (0-9)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Quinn Emanuel',
    url: 'https://www.quinnemanuel.com',
    industry: ['law-firm'],
    styleTags: ['corporate', 'modern', 'minimalist'],
    colorSamples: ['#1B2A4A', '#FFFFFF', '#C9A96E', '#F5F5F5'],
    sectionTypes: ['navigation', 'hero', 'about', 'stats', 'testimonials', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Authoritative law firm site with a navy and gold palette, serif headings, and a commanding hero section that conveys prestige.',
    displayOrder: 0,
  },
  {
    name: 'Kirkland & Ellis',
    url: 'https://www.kirkland.com',
    industry: ['law-firm'],
    styleTags: ['corporate', 'elegant', 'dark-mode'],
    colorSamples: ['#0A1628', '#FFFFFF', '#8B7355', '#2C3E50'],
    sectionTypes: ['navigation', 'hero', 'about', 'stats', 'team', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Dark-toned corporate design with restrained typography and understated luxury cues. Prioritizes content hierarchy and credibility.',
    displayOrder: 1,
  },
  {
    name: 'Latham & Watkins',
    url: 'https://www.lw.com',
    industry: ['law-firm'],
    styleTags: ['corporate', 'modern', 'geometric'],
    colorSamples: ['#003366', '#FFFFFF', '#E8E8E8', '#FF6600'],
    sectionTypes: ['navigation', 'hero', 'features', 'about', 'stats', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Clean, modern law firm site with geometric section dividers and a bold orange accent against deep navy. Feels approachable yet professional.',
    displayOrder: 2,
  },
  {
    name: 'Cravath, Swaine & Moore',
    url: 'https://www.cravath.com',
    industry: ['law-firm'],
    styleTags: ['elegant', 'minimalist', 'corporate'],
    colorSamples: ['#1C3553', '#FFFFFF', '#D4AF37', '#F0EDE8'],
    sectionTypes: ['navigation', 'hero', 'about', 'team', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Timeless and refined design reflecting decades of legal tradition. Gold accents on muted backgrounds with generous white space.',
    displayOrder: 3,
  },
  {
    name: 'Wachtell, Lipton, Rosen & Katz',
    url: 'https://www.wlrk.com',
    industry: ['law-firm'],
    styleTags: ['minimalist', 'corporate', 'elegant'],
    colorSamples: ['#2B2B2B', '#FFFFFF', '#7A6A53', '#F8F8F8'],
    sectionTypes: ['navigation', 'hero', 'about', 'team', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Ultra-minimalist single-column layout with restrained color and serif typography that projects quiet confidence and exclusivity.',
    displayOrder: 4,
  },
  {
    name: 'Baker McKenzie',
    url: 'https://www.bakermckenzie.com',
    industry: ['law-firm'],
    styleTags: ['modern', 'bold', 'corporate'],
    colorSamples: ['#003A70', '#FFFFFF', '#00A3E0', '#333333'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'about', 'cta', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Global law firm with a modern grid layout, bright blue accents, and card-based content sections that showcase worldwide reach.',
    displayOrder: 5,
  },
  {
    name: 'DLA Piper',
    url: 'https://www.dlapiper.com',
    industry: ['law-firm'],
    styleTags: ['corporate', 'modern', 'gradient'],
    colorSamples: ['#1E3A5F', '#FFFFFF', '#4A90D9', '#F5F5F5', '#333333'],
    sectionTypes: ['navigation', 'hero', 'features', 'about', 'stats', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Full-width sections with subtle blue gradients and a content-heavy approach. Modern sans-serif type with clear content segmentation.',
    displayOrder: 6,
  },
  {
    name: 'Skadden, Arps',
    url: 'https://www.skadden.com',
    industry: ['law-firm'],
    styleTags: ['elegant', 'dark-mode', 'minimalist'],
    colorSamples: ['#0D1B2A', '#FFFFFF', '#A68B5B', '#1B2838'],
    sectionTypes: ['navigation', 'hero', 'about', 'features', 'team', 'contact', 'footer'],
    typography: 'mixed',
    layoutStyle: 'single-column',
    description:
      'Sophisticated dark-mode design with warm gold highlights. Mixed serif headings and sans-serif body create a premium editorial feel.',
    displayOrder: 7,
  },
  {
    name: 'Clifford Chance',
    url: 'https://www.cliffordchance.com',
    industry: ['law-firm'],
    styleTags: ['modern', 'corporate', 'geometric'],
    colorSamples: ['#00263A', '#FFFFFF', '#00B5E2', '#E6E6E6', '#FF5C00'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'about', 'gallery', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'International firm with a dynamic grid layout, teal and orange accents, and geometric shapes framing content blocks.',
    displayOrder: 8,
  },
  {
    name: 'Gibson Dunn',
    url: 'https://www.gibsondunn.com',
    industry: ['law-firm'],
    styleTags: ['corporate', 'elegant', 'modern'],
    colorSamples: ['#1A2744', '#FFFFFF', '#B8860B', '#EEEEEE'],
    sectionTypes: ['navigation', 'hero', 'about', 'features', 'team', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'two-column',
    description:
      'Two-column layout balancing rich imagery with detailed firm information. Serif headings paired with a navy-gold palette convey authority.',
    displayOrder: 9,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SAAS (10-19)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Linear',
    url: 'https://linear.app',
    industry: ['saas'],
    styleTags: ['minimalist', 'dark-mode', 'modern'],
    colorSamples: ['#000000', '#FFFFFF', '#5E6AD2', '#1D1D1D', '#888888'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Iconic dark-mode SaaS design with buttery smooth animations, a purple accent, and pixel-perfect typography that set the standard for dev tools.',
    displayOrder: 10,
  },
  {
    name: 'Vercel',
    url: 'https://vercel.com',
    industry: ['saas'],
    styleTags: ['minimalist', 'dark-mode', 'tech'],
    colorSamples: ['#000000', '#FFFFFF', '#0070F3', '#171717', '#888888'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Crisp black-and-white aesthetic with blue link accents. Full-width sections with code snippets and deploy previews showcase developer-first thinking.',
    displayOrder: 11,
  },
  {
    name: 'Notion',
    url: 'https://www.notion.so',
    industry: ['saas'],
    styleTags: ['minimalist', 'playful', 'modern'],
    colorSamples: ['#FFFFFF', '#000000', '#E16259', '#F7F6F3', '#37352F'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'gallery',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Warm and approachable SaaS design with a cream background, hand-drawn illustration accents, and playful micro-interactions that make productivity feel delightful.',
    displayOrder: 12,
  },
  {
    name: 'Stripe',
    url: 'https://stripe.com',
    industry: ['saas', 'finance'],
    styleTags: ['gradient', 'modern', 'elegant'],
    colorSamples: ['#635BFF', '#0A2540', '#00D4AA', '#FFFFFF', '#425466'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'The gold standard in SaaS web design featuring rich gradients, animated code blocks, and a purple-teal palette that balances technical depth with visual elegance.',
    displayOrder: 13,
  },
  {
    name: 'Figma',
    url: 'https://www.figma.com',
    industry: ['saas'],
    styleTags: ['bold', 'playful', 'modern'],
    colorSamples: ['#0D0D0D', '#FFFFFF', '#A259FF', '#1ABCFE', '#0ACF83'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'pricing',
      'gallery',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Vibrant multi-color brand with bold section breaks and interactive product demos embedded directly in the page. Design-forward and community-driven.',
    displayOrder: 14,
  },
  {
    name: 'Loom',
    url: 'https://www.loom.com',
    industry: ['saas'],
    styleTags: ['modern', 'playful', 'gradient'],
    colorSamples: ['#625DF5', '#FFFFFF', '#F5F3FF', '#1D1D1D', '#FF6B6B'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Friendly, video-first SaaS marketing site with soft purple gradients, inline video demos, and rounded corners throughout the interface.',
    displayOrder: 15,
  },
  {
    name: 'Raycast',
    url: 'https://www.raycast.com',
    industry: ['saas'],
    styleTags: ['dark-mode', 'tech', 'minimalist'],
    colorSamples: ['#131313', '#FFFFFF', '#FF6363', '#1A1A1A', '#666666'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Developer productivity tool with an ultra-dark theme, red accent color, and keyboard-shortcut-inspired UI patterns that appeal to power users.',
    displayOrder: 16,
  },
  {
    name: 'Slack',
    url: 'https://slack.com',
    industry: ['saas'],
    styleTags: ['bold', 'playful', 'modern'],
    colorSamples: ['#4A154B', '#FFFFFF', '#36C5F0', '#2EB67D', '#ECB22E'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'stats',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Energetic four-color brand identity with bold typography, product screenshots, and playful illustrations that make enterprise collaboration feel approachable.',
    displayOrder: 17,
  },
  {
    name: 'Framer',
    url: 'https://www.framer.com',
    industry: ['saas'],
    styleTags: ['bold', 'dark-mode', 'modern'],
    colorSamples: ['#0D0D0D', '#FFFFFF', '#0099FF', '#1A1A1A', '#666666'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'gallery',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Sleek dark-mode design tool site with interactive demos, blue accents, and scroll-triggered animations that showcase the product capabilities.',
    displayOrder: 18,
  },
  {
    name: 'Resend',
    url: 'https://resend.com',
    industry: ['saas'],
    styleTags: ['minimalist', 'dark-mode', 'tech'],
    colorSamples: ['#000000', '#FFFFFF', '#00C4B4', '#1A1A1A', '#888888'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'pricing', 'cta', 'footer'],
    typography: 'mono',
    layoutStyle: 'single-column',
    description:
      'Developer email API with a stark dark background, monospace type for code emphasis, and teal highlights that nod to terminal aesthetics.',
    displayOrder: 19,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // AGENCY (20-29)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Pentagram',
    url: 'https://www.pentagram.com',
    industry: ['agency'],
    styleTags: ['minimalist', 'editorial', 'elegant'],
    colorSamples: ['#000000', '#FFFFFF', '#E8E8E8', '#333333'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'team', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'grid',
    description:
      'World-renowned design consultancy with a grid-based portfolio layout. Pure black-and-white palette lets the case study imagery take center stage.',
    displayOrder: 20,
  },
  {
    name: 'Huge',
    url: 'https://www.hugeinc.com',
    industry: ['agency'],
    styleTags: ['bold', 'modern', 'dark-mode'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#FF4D00', '#1A1A1A', '#CCCCCC'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'about',
      'features',
      'team',
      'contact',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Bold digital agency site with oversized typography, a striking orange accent, and full-bleed project imagery on a dark canvas.',
    displayOrder: 21,
  },
  {
    name: 'R/GA',
    url: 'https://www.rga.com',
    industry: ['agency'],
    styleTags: ['modern', 'tech', 'minimalist'],
    colorSamples: ['#000000', '#FFFFFF', '#00FF87', '#1A1A1A', '#888888'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'stats', 'team', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Innovation-focused agency with a tech-forward aesthetic. Neon green accents against black create an energetic digital-native feel.',
    displayOrder: 22,
  },
  {
    name: 'Instrument',
    url: 'https://www.instrument.com',
    industry: ['agency'],
    styleTags: ['minimalist', 'elegant', 'editorial'],
    colorSamples: ['#FFFFFF', '#000000', '#F0F0F0', '#333333'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'testimonials', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Portland-based digital agency with a clean single-column portfolio. Generous white space and oversized project imagery create an editorial gallery feel.',
    displayOrder: 23,
  },
  {
    name: 'Locomotive',
    url: 'https://locomotive.ca',
    industry: ['agency'],
    styleTags: ['bold', 'playful', 'modern'],
    colorSamples: ['#0E0E0E', '#FFFFFF', '#FF3333', '#1A1A1A', '#F5F5F5'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'team', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'asymmetric',
    description:
      'Award-winning creative studio with dynamic scroll animations, asymmetric layouts, and bold red accents. Known for pushing web interaction boundaries.',
    displayOrder: 24,
  },
  {
    name: 'Basic Agency',
    url: 'https://www.basicagency.com',
    industry: ['agency'],
    styleTags: ['minimalist', 'modern', 'elegant'],
    colorSamples: ['#FFFFFF', '#000000', '#F5F5F5', '#CCCCCC'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'testimonials', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'San Diego branding agency with an ultra-clean grid portfolio. Monochrome palette with carefully curated case study cards and smooth hover states.',
    displayOrder: 25,
  },
  {
    name: 'Fantasy',
    url: 'https://fantasy.co',
    industry: ['agency'],
    styleTags: ['dark-mode', 'modern', 'tech'],
    colorSamples: ['#111111', '#FFFFFF', '#5A5AFF', '#1D1D1D', '#AAAAAA'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'stats', 'team', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'UX design agency with a dark, immersive presentation style. Blue-violet accents and full-width video backgrounds create a cinematic portfolio experience.',
    displayOrder: 26,
  },
  {
    name: 'Work & Co',
    url: 'https://work.co',
    industry: ['agency'],
    styleTags: ['bold', 'minimalist', 'modern'],
    colorSamples: ['#FFFFFF', '#000000', '#FF0000', '#F8F8F8'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'team', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Product design studio with a stark black-white-red palette. Large-scale typography and full-bleed project imagery dominate the single-column flow.',
    displayOrder: 27,
  },
  {
    name: 'Rally Interactive',
    url: 'https://rallyinteractive.com',
    industry: ['agency'],
    styleTags: ['organic', 'elegant', 'modern'],
    colorSamples: ['#F5F0EB', '#2B2B2B', '#D4A574', '#FFFFFF', '#666666'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'testimonials', 'footer'],
    typography: 'mixed',
    layoutStyle: 'asymmetric',
    description:
      'Warm, tactile agency site with organic textures, earthy tones, and asymmetric layouts. Serif-sans pairings evoke a handcrafted design philosophy.',
    displayOrder: 28,
  },
  {
    name: 'ueno',
    url: 'https://ueno.co',
    industry: ['agency'],
    styleTags: ['playful', 'bold', 'gradient'],
    colorSamples: ['#FFFFFF', '#000000', '#FF6B6B', '#4ECDC4', '#556270'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'team', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Playful digital agency with gradient overlays, colorful transitions, and personality-driven team pages. Balances fun with world-class craft.',
    displayOrder: 29,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // ECOMMERCE (30-39)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Allbirds',
    url: 'https://www.allbirds.com',
    industry: ['ecommerce'],
    styleTags: ['organic', 'minimalist', 'modern'],
    colorSamples: ['#FFFFFF', '#2D3436', '#3D9970', '#F1F0EB', '#D4C5A9'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Sustainable footwear brand with an earthy, nature-inspired palette and clean product photography. Organic greens and warm neutrals reinforce eco-messaging.',
    displayOrder: 30,
  },
  {
    name: 'Glossier',
    url: 'https://www.glossier.com',
    industry: ['ecommerce'],
    styleTags: ['minimalist', 'playful', 'modern'],
    colorSamples: ['#FFFFFF', '#FE3E7A', '#F9F0E7', '#2B2B2B', '#FFD1DC'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Millennial pink beauty brand with an editorial grid layout. Soft tones, user-generated content, and playful hover animations create an intimate shopping experience.',
    displayOrder: 31,
  },
  {
    name: 'Everlane',
    url: 'https://www.everlane.com',
    industry: ['ecommerce'],
    styleTags: ['minimalist', 'elegant', 'modern'],
    colorSamples: ['#FFFFFF', '#000000', '#F5F5F0', '#333333', '#C9B99A'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Transparency-focused fashion retailer with a muted neutral palette, clean product grids, and cost-breakdown infographics that build consumer trust.',
    displayOrder: 32,
  },
  {
    name: 'Apple Store',
    url: 'https://www.apple.com/store',
    industry: ['ecommerce'],
    styleTags: ['minimalist', 'modern', 'elegant'],
    colorSamples: ['#FFFFFF', '#1D1D1F', '#0071E3', '#F5F5F7', '#86868B'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'The benchmark for product-focused ecommerce. Massive hero images, minimal text, and a pristine white canvas let products speak for themselves.',
    displayOrder: 33,
  },
  {
    name: 'Aesop',
    url: 'https://www.aesop.com',
    industry: ['ecommerce'],
    styleTags: ['elegant', 'organic', 'luxurious'],
    colorSamples: ['#FFFEF2', '#252422', '#C17817', '#E8DED1', '#5C5347'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Luxury skincare brand with warm ochre tones, textured backgrounds, and serif typography that evokes artisanal apothecary heritage.',
    displayOrder: 34,
  },
  {
    name: 'Warby Parker',
    url: 'https://www.warbyparker.com',
    industry: ['ecommerce'],
    styleTags: ['playful', 'modern', 'bold'],
    colorSamples: ['#FFFFFF', '#00ACB8', '#1D3461', '#F7F7F7', '#FDB927'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Eyewear DTC brand with a teal and navy palette, virtual try-on integration, and friendly grid-based product browsing that simplifies selection.',
    displayOrder: 35,
  },
  {
    name: 'Mejuri',
    url: 'https://mejuri.com',
    industry: ['ecommerce'],
    styleTags: ['elegant', 'minimalist', 'luxurious'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#C5A880', '#F5F1EB', '#333333'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Fine jewelry ecommerce with a luxurious gold-and-cream palette, editorial product photography, and a clean grid that highlights each piece.',
    displayOrder: 36,
  },
  {
    name: 'Gymshark',
    url: 'https://www.gymshark.com',
    industry: ['ecommerce'],
    styleTags: ['bold', 'dark-mode', 'modern'],
    colorSamples: ['#1A1A1A', '#FFFFFF', '#00B4D8', '#2D2D2D', '#E63946'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'High-energy fitness apparel brand with a dark theme, bold lifestyle photography, and athletic typography that targets the gym community.',
    displayOrder: 37,
  },
  {
    name: 'Away',
    url: 'https://www.awaytravel.com',
    industry: ['ecommerce'],
    styleTags: ['modern', 'minimalist', 'elegant'],
    colorSamples: ['#FFFFFF', '#1D3557', '#E8E4DE', '#457B9D', '#F1FAEE'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Travel luggage brand with muted blues and warm neutrals. Full-width lifestyle imagery and clean product specs create aspirational yet informative shopping.',
    displayOrder: 38,
  },
  {
    name: 'Casper',
    url: 'https://casper.com',
    industry: ['ecommerce'],
    styleTags: ['playful', 'modern', 'organic'],
    colorSamples: ['#FFFFFF', '#1F3044', '#5DADE2', '#F4F0E8', '#AADCF0'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'stats',
      'pricing',
      'faq',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Sleep-focused DTC brand with dreamy blue tones, playful illustrations, and a reassuring design that addresses purchase anxiety with FAQs and reviews.',
    displayOrder: 39,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PORTFOLIO (40-49)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Brittany Chiang',
    url: 'https://brittanychiang.com',
    industry: ['portfolio'],
    styleTags: ['dark-mode', 'tech', 'minimalist'],
    colorSamples: ['#0A192F', '#CCD6F6', '#64FFDA', '#112240', '#8892B0'],
    sectionTypes: ['navigation', 'hero', 'about', 'features', 'gallery', 'contact', 'footer'],
    typography: 'mono',
    layoutStyle: 'single-column',
    description:
      'Software engineer portfolio with a navy dark theme and mint green accents. Monospace type and numbered sections evoke a terminal-inspired aesthetic.',
    displayOrder: 40,
  },
  {
    name: 'Tobias van Schneider',
    url: 'https://vanschneider.com',
    industry: ['portfolio'],
    styleTags: ['bold', 'editorial', 'dark-mode'],
    colorSamples: ['#111111', '#FFFFFF', '#FFD700', '#1A1A1A', '#999999'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Designer and creator portfolio with bold yellow accents on a dark canvas. Editorial blog-style layout showcases both work and personal writing.',
    displayOrder: 41,
  },
  {
    name: 'Refactoring UI',
    url: 'https://www.refactoringui.com',
    industry: ['portfolio'],
    styleTags: ['modern', 'gradient', 'tech'],
    colorSamples: ['#1A202C', '#FFFFFF', '#6C63FF', '#2D3748', '#A0AEC0'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Design resource portfolio combining product marketing with educational content. Purple gradient hero with before-and-after UI examples throughout.',
    displayOrder: 42,
  },
  {
    name: 'Adham Dannaway',
    url: 'https://www.adhamdannaway.com',
    industry: ['portfolio'],
    styleTags: ['modern', 'bold', 'geometric'],
    colorSamples: ['#FFFFFF', '#2C3E50', '#3498DB', '#F0F0F0', '#E74C3C'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'testimonials', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'UI/UX designer portfolio with an iconic split-screen hero (designer vs developer). Clean geometric cards showcase case studies with clear hierarchy.',
    displayOrder: 43,
  },
  {
    name: 'Lapa Ninja',
    url: 'https://www.lapa.ninja',
    industry: ['portfolio'],
    styleTags: ['minimalist', 'modern', 'elegant'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#FF5A5F', '#F7F7F7', '#333333'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Design inspiration gallery with a clean masonry grid layout. Minimal interface with red accent keeps focus on the curated website screenshots.',
    displayOrder: 44,
  },
  {
    name: 'Josh W Comeau',
    url: 'https://www.joshwcomeau.com',
    industry: ['portfolio'],
    styleTags: ['playful', 'modern', 'gradient'],
    colorSamples: ['#0F172A', '#F8FAFC', '#FF6B9D', '#C084FC', '#22D3EE'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'features', 'cta', 'footer'],
    typography: 'mixed',
    layoutStyle: 'single-column',
    description:
      'Developer educator portfolio with whimsical gradient accents, interactive code demos, and a warm personality. Pink-purple palette on dark background.',
    displayOrder: 45,
  },
  {
    name: 'Dejan Markovic',
    url: 'https://www.dejan.works',
    industry: ['portfolio'],
    styleTags: ['brutalist', 'bold', 'dark-mode'],
    colorSamples: ['#0D0D0D', '#FFFFFF', '#FF4444', '#1A1A1A', '#888888'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'asymmetric',
    description:
      'Product designer portfolio with brutalist sensibility. Oversized type, red accents, and unconventional asymmetric layouts create a provocative first impression.',
    displayOrder: 46,
  },
  {
    name: 'Rauno Freiberg',
    url: 'https://rauno.me',
    industry: ['portfolio'],
    styleTags: ['minimalist', 'elegant', 'modern'],
    colorSamples: ['#FFFFFF', '#111111', '#666666', '#F5F5F5', '#999999'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Interaction designer portfolio with extreme minimalism. Barely any color, letting subtle animations and micro-interactions demonstrate craft.',
    displayOrder: 47,
  },
  {
    name: 'Paco Coursey',
    url: 'https://paco.me',
    industry: ['portfolio'],
    styleTags: ['minimalist', 'dark-mode', 'tech'],
    colorSamples: ['#111111', '#EEEEEE', '#888888', '#1A1A1A', '#555555'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'footer'],
    typography: 'mono',
    layoutStyle: 'single-column',
    description:
      'Developer portfolio with a stripped-back dark aesthetic. Monospace type, minimal navigation, and a focus on writing and open-source projects.',
    displayOrder: 48,
  },
  {
    name: 'Dennis Snellenberg',
    url: 'https://dennissnellenberg.com',
    industry: ['portfolio'],
    styleTags: ['bold', 'modern', 'elegant'],
    colorSamples: ['#1A1A1A', '#FFFFFF', '#C5A47E', '#0D0D0D', '#888888'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Freelance developer portfolio with smooth page transitions, a gold serif wordmark, and full-width project showcases with cursor-following effects.',
    displayOrder: 49,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // RESTAURANT (50-59)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Eleven Madison Park',
    url: 'https://www.elevenmadisonpark.com',
    industry: ['restaurant'],
    styleTags: ['elegant', 'minimalist', 'luxurious'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#C9A96E', '#F5F2ED', '#4A4A4A'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Three-Michelin-star restaurant with an understated, gallery-like website. Serif typography and ample white space reflect the dining precision.',
    displayOrder: 50,
  },
  {
    name: 'Noma',
    url: 'https://noma.dk',
    industry: ['restaurant'],
    styleTags: ['organic', 'minimalist', 'editorial'],
    colorSamples: ['#F5F0E8', '#2C2C2C', '#8B7355', '#FFFFFF', '#666666'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Iconic Nordic restaurant with a warm, paper-textured aesthetic. Editorial photography and muted earth tones channel the philosophy of foraging and seasons.',
    displayOrder: 51,
  },
  {
    name: 'Alinea',
    url: 'https://www.alinearestaurant.com',
    industry: ['restaurant'],
    styleTags: ['dark-mode', 'luxurious', 'modern'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#C8A96E', '#1A1A1A', '#888888'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Progressive fine dining with a dramatic dark-mode site. Gold accents and cinematic food photography set the tone for an avant-garde culinary experience.',
    displayOrder: 52,
  },
  {
    name: 'Nobu',
    url: 'https://www.noburestaurants.com',
    industry: ['restaurant'],
    styleTags: ['luxurious', 'elegant', 'modern'],
    colorSamples: ['#1C1C1C', '#FFFFFF', '#B8860B', '#2D2D2D', '#E8E0D0'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'features', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Global Japanese restaurant chain with a dark, sophisticated design. Full-width imagery and gold-on-black palette convey luxury dining across locations.',
    displayOrder: 53,
  },
  {
    name: 'Sweetgreen',
    url: 'https://www.sweetgreen.com',
    industry: ['restaurant'],
    styleTags: ['organic', 'playful', 'modern'],
    colorSamples: ['#FFFFFF', '#2D6A4F', '#95D5B2', '#F0F4EF', '#1B4332'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Fast-casual salad chain with a fresh green palette and lifestyle-driven photography. Clean design with organic shapes reinforces the farm-to-table brand.',
    displayOrder: 54,
  },
  {
    name: 'Dishoom',
    url: 'https://www.dishoom.com',
    industry: ['restaurant'],
    styleTags: ['vintage', 'elegant', 'editorial'],
    colorSamples: ['#F5EDE0', '#2B1B12', '#C4A35A', '#D4C4A8', '#5C3D2E'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'features', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Bombay-inspired cafe with a nostalgic vintage aesthetic. Sepia tones, retro photography, and ornate serif type evoke colonial-era Irani cafes.',
    displayOrder: 55,
  },
  {
    name: 'The French Laundry',
    url: 'https://www.thomaskeller.com/tfl',
    industry: ['restaurant'],
    styleTags: ['elegant', 'luxurious', 'minimalist'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#7B6D5B', '#F8F5F0', '#B39C7D'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Thomas Keller flagship restaurant with a refined, gallery-like web presence. Muted stone colors and elegant serif type mirror the culinary artistry.',
    displayOrder: 56,
  },
  {
    name: 'Shake Shack',
    url: 'https://www.shakeshack.com',
    industry: ['restaurant'],
    styleTags: ['bold', 'playful', 'modern'],
    colorSamples: ['#1D7044', '#FFFFFF', '#000000', '#F5F5F5', '#E8E8E8'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Fast-casual burger chain with a signature green-black palette. Bold typography and mouth-watering food photography drive appetite and brand recognition.',
    displayOrder: 57,
  },
  {
    name: 'Blue Bottle Coffee',
    url: 'https://bluebottlecoffee.com',
    industry: ['restaurant'],
    styleTags: ['minimalist', 'organic', 'elegant'],
    colorSamples: ['#FFFFFF', '#2C3E50', '#6AAFE6', '#F5F3EF', '#333333'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Specialty coffee brand with a calm, pared-back aesthetic. Soft blue accents on white with grid-based product displays reflect artisanal precision.',
    displayOrder: 58,
  },
  {
    name: 'Eataly',
    url: 'https://www.eataly.com',
    industry: ['restaurant'],
    styleTags: ['bold', 'vintage', 'editorial'],
    colorSamples: ['#FFFFFF', '#B22222', '#1A1A1A', '#F5F0E0', '#2E8B57'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'contact', 'footer'],
    typography: 'mixed',
    layoutStyle: 'grid',
    description:
      'Italian food marketplace with a rustic editorial grid. Red-green-white Italian palette, mixed typography, and rich food photography celebrate culinary culture.',
    displayOrder: 59,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // HEALTHCARE (60-69)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'One Medical',
    url: 'https://www.onemedical.com',
    industry: ['healthcare'],
    styleTags: ['modern', 'minimalist', 'organic'],
    colorSamples: ['#FFFFFF', '#1B365D', '#00A87E', '#F5F7FA', '#4A4A4A'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'stats',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Modern primary care with a calming blue-green palette and approachable sans-serif type. Clean layout builds trust while feeling contemporary and tech-forward.',
    displayOrder: 60,
  },
  {
    name: 'Hims & Hers',
    url: 'https://www.forhims.com',
    industry: ['healthcare'],
    styleTags: ['modern', 'playful', 'minimalist'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#F2E8DF', '#5C9EAD', '#E8B4B8'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'gallery',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Telehealth brand with a soft, gender-neutral pastel palette. Friendly illustrations and a conversational tone destigmatize health consultations.',
    displayOrder: 61,
  },
  {
    name: 'Ro',
    url: 'https://ro.co',
    industry: ['healthcare'],
    styleTags: ['minimalist', 'modern', 'tech'],
    colorSamples: ['#FFFFFF', '#0B2545', '#13678A', '#F0F4F8', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Digital health clinic with a clean, trustworthy blue palette. Data-driven stats sections and clear CTAs guide patients through telehealth onboarding.',
    displayOrder: 62,
  },
  {
    name: 'Calm',
    url: 'https://www.calm.com',
    industry: ['healthcare'],
    styleTags: ['organic', 'gradient', 'modern'],
    colorSamples: ['#1F3A5F', '#FFFFFF', '#7DB9DE', '#92CCA6', '#F5EEE6'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Mental wellness app with soothing blue-green gradients and nature-inspired imagery. Full-width sections create an immersive, relaxing browsing experience.',
    displayOrder: 63,
  },
  {
    name: 'Headspace',
    url: 'https://www.headspace.com',
    industry: ['healthcare'],
    styleTags: ['playful', 'bold', 'modern'],
    colorSamples: ['#F47D31', '#FFFFFF', '#2C2D41', '#FCE4A8', '#FF8E71'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Meditation app with a distinctive warm orange palette and charming character illustrations. Playful design makes mindfulness feel welcoming and non-intimidating.',
    displayOrder: 64,
  },
  {
    name: 'Oscar Health',
    url: 'https://www.hioscar.com',
    industry: ['healthcare', 'finance'],
    styleTags: ['modern', 'bold', 'playful'],
    colorSamples: ['#FFFFFF', '#1B1B1B', '#FF6B00', '#F5F5F5', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Health insurance disruptor with a bold orange brand color and friendly illustrations. Simplifies complex healthcare information with clear visual hierarchy.',
    displayOrder: 65,
  },
  {
    name: 'Zocdoc',
    url: 'https://www.zocdoc.com',
    industry: ['healthcare'],
    styleTags: ['modern', 'playful', 'bold'],
    colorSamples: ['#FFFFFF', '#2E2F85', '#4CD5C5', '#F8F8F8', '#FF7D60'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'stats',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Doctor booking platform with a vibrant purple-teal-coral palette and quirky character illustrations. Search-first design prioritizes instant utility.',
    displayOrder: 66,
  },
  {
    name: 'Nurx',
    url: 'https://www.nurx.com',
    industry: ['healthcare'],
    styleTags: ['modern', 'minimalist', 'elegant'],
    colorSamples: ['#FFFFFF', '#2D2D4E', '#E8739A', '#F5F0F6', '#666666'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'faq', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Telehealth prescription service with soft purple and pink tones. Clean, reassuring design with testimonials and FAQ sections that build patient confidence.',
    displayOrder: 67,
  },
  {
    name: 'Noom',
    url: 'https://www.noom.com',
    industry: ['healthcare'],
    styleTags: ['bold', 'modern', 'gradient'],
    colorSamples: ['#FFFFFF', '#FF6F00', '#1A1A1A', '#FFF3E0', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'stats',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Weight management app with a bold orange-to-yellow gradient identity. Data-forward design with progress stats and before-after testimonials.',
    displayOrder: 68,
  },
  {
    name: 'Cerebral',
    url: 'https://cerebral.com',
    industry: ['healthcare'],
    styleTags: ['modern', 'organic', 'minimalist'],
    colorSamples: ['#FFFFFF', '#1A3B47', '#7FB3B4', '#F0F7F4', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'faq',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Online mental health care platform with calming teal-green tones and organic rounded shapes. Clinical credibility balanced with approachable warmth.',
    displayOrder: 69,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // FINANCE (70-79)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Mercury',
    url: 'https://mercury.com',
    industry: ['finance', 'saas'],
    styleTags: ['dark-mode', 'modern', 'tech'],
    colorSamples: ['#0E0E2C', '#FFFFFF', '#6C63FF', '#1A1A3E', '#B8B8D1'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Startup banking platform with a deep-space dark theme and electric purple accents. Product screenshots and API docs signal developer-friendly fintech.',
    displayOrder: 70,
  },
  {
    name: 'Ramp',
    url: 'https://ramp.com',
    industry: ['finance', 'saas'],
    styleTags: ['modern', 'bold', 'tech'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#FFD700', '#F5F5F5', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Corporate card and expense management with a confident black-and-gold palette. Data visualizations and savings stats front-and-center to drive conversion.',
    displayOrder: 71,
  },
  {
    name: 'Brex',
    url: 'https://www.brex.com',
    industry: ['finance', 'saas'],
    styleTags: ['modern', 'gradient', 'bold'],
    colorSamples: ['#000000', '#FFFFFF', '#FF5F00', '#1A1A1A', '#FF9E4F'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Business financial platform with bold orange gradients on dark backgrounds. Product-led growth design with interactive demos and social proof.',
    displayOrder: 72,
  },
  {
    name: 'Wise',
    url: 'https://wise.com',
    industry: ['finance'],
    styleTags: ['modern', 'playful', 'bold'],
    colorSamples: ['#FFFFFF', '#163300', '#9FE870', '#F0F0F0', '#37517E'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'International money transfer with a distinctive bright green brand color. Transparent pricing calculators and real-time rate widgets build instant trust.',
    displayOrder: 73,
  },
  {
    name: 'Robinhood',
    url: 'https://robinhood.com',
    industry: ['finance'],
    styleTags: ['modern', 'bold', 'gradient'],
    colorSamples: ['#1E2124', '#FFFFFF', '#00C805', '#1A1A1A', '#5AC53A'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Trading platform with a signature green-on-dark palette. Gradient backgrounds and stock chart visualizations create a dynamic, market-driven aesthetic.',
    displayOrder: 74,
  },
  {
    name: 'Wealthsimple',
    url: 'https://www.wealthsimple.com',
    industry: ['finance'],
    styleTags: ['minimalist', 'elegant', 'modern'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#FFD700', '#F5F5F5', '#666666'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'stats', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Canadian investing platform with an editorial magazine aesthetic. Serif headings and gold accents position automated investing as a premium lifestyle choice.',
    displayOrder: 75,
  },
  {
    name: 'Revolut',
    url: 'https://www.revolut.com',
    industry: ['finance'],
    styleTags: ['dark-mode', 'modern', 'tech'],
    colorSamples: ['#0D0D0D', '#FFFFFF', '#0075EB', '#1A1A1A', '#888888'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'pricing',
      'testimonials',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Global super-app with a sleek dark interface and electric blue accents. Product feature cards and device mockups showcase the all-in-one financial platform.',
    displayOrder: 76,
  },
  {
    name: 'Coinbase',
    url: 'https://www.coinbase.com',
    industry: ['finance'],
    styleTags: ['bold', 'modern', 'dark-mode'],
    colorSamples: ['#0052FF', '#FFFFFF', '#000000', '#050F1A', '#888888'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Cryptocurrency exchange with a bold blue brand identity. Clean data tables, real-time price feeds, and an educational approach simplify complex financial products.',
    displayOrder: 77,
  },
  {
    name: 'Chime',
    url: 'https://www.chime.com',
    industry: ['finance'],
    styleTags: ['modern', 'playful', 'gradient'],
    colorSamples: ['#FFFFFF', '#1EC677', '#1A1A1A', '#F0FFF4', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'stats',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Digital banking with a cheerful green palette and rounded UI elements. Benefit-focused messaging and trust badges address financial anxiety head-on.',
    displayOrder: 78,
  },
  {
    name: 'N26',
    url: 'https://n26.com',
    industry: ['finance'],
    styleTags: ['modern', 'minimalist', 'elegant'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#36A18B', '#F5F5F5', '#555555'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'pricing',
      'testimonials',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'European digital bank with a refined teal-and-monochrome palette. Clean product comparisons and tier-based pricing tables dominate the conversion funnel.',
    displayOrder: 79,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // REAL ESTATE (80-89)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Compass',
    url: 'https://www.compass.com',
    industry: ['real-estate'],
    styleTags: ['modern', 'elegant', 'minimalist'],
    colorSamples: ['#FFFFFF', '#000000', '#B8860B', '#F5F5F5', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'gallery',
      'testimonials',
      'cta',
      'contact',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Real estate tech platform with a luxe black-gold-white palette. Search-first hero with property cards and neighborhood guides blend utility with aspiration.',
    displayOrder: 80,
  },
  {
    name: "Sotheby's International Realty",
    url: 'https://www.sothebysrealty.com',
    industry: ['real-estate'],
    styleTags: ['luxurious', 'elegant', 'corporate'],
    colorSamples: ['#FFFFFF', '#002349', '#B8860B', '#F0EDE8', '#4A4A4A'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'stats', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Luxury real estate brand with a navy-and-gold palette and serif headings. Full-width property photography and curated collections exude exclusivity.',
    displayOrder: 81,
  },
  {
    name: 'Zillow',
    url: 'https://www.zillow.com',
    industry: ['real-estate'],
    styleTags: ['modern', 'bold', 'tech'],
    colorSamples: ['#FFFFFF', '#006AFF', '#1A1A1A', '#F5F5F5', '#333333'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Dominant real estate marketplace with a bold blue brand and search-centric UX. Data-heavy property cards with Zestimate pricing and map integration.',
    displayOrder: 82,
  },
  {
    name: 'Redfin',
    url: 'https://www.redfin.com',
    industry: ['real-estate'],
    styleTags: ['modern', 'bold', 'tech'],
    colorSamples: ['#FFFFFF', '#A02B2D', '#1A1A1A', '#F5F5F5', '#333333'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Tech-driven real estate brokerage with a distinctive red brand. Map-first search experience with commission savings prominently displayed.',
    displayOrder: 83,
  },
  {
    name: 'The Agency',
    url: 'https://www.theagencyre.com',
    industry: ['real-estate'],
    styleTags: ['luxurious', 'dark-mode', 'elegant'],
    colorSamples: ['#1A1A1A', '#FFFFFF', '#C8A97E', '#0D0D0D', '#888888'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'about',
      'team',
      'testimonials',
      'contact',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Luxury brokerage with a cinematic dark-mode design. Gold accents, full-bleed property photography, and video tours create an immersive browsing experience.',
    displayOrder: 84,
  },
  {
    name: 'Douglas Elliman',
    url: 'https://www.elliman.com',
    industry: ['real-estate'],
    styleTags: ['elegant', 'corporate', 'modern'],
    colorSamples: ['#FFFFFF', '#1A2B4A', '#C9A96E', '#F5F5F5', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'features',
      'stats',
      'team',
      'contact',
      'footer',
    ],
    typography: 'serif',
    layoutStyle: 'grid',
    description:
      'Premium real estate firm with a grid-based property showcase. Navy and gold branding with serif headings project established prestige across markets.',
    displayOrder: 85,
  },
  {
    name: 'Opendoor',
    url: 'https://www.opendoor.com',
    industry: ['real-estate'],
    styleTags: ['modern', 'playful', 'bold'],
    colorSamples: ['#FFFFFF', '#5B2EAA', '#1A1A1A', '#F5F0FF', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'iBuyer platform with a distinctive purple brand color. Simplified selling flow with step-by-step illustrations and instant offer calculators.',
    displayOrder: 86,
  },
  {
    name: 'Engel & Volkers',
    url: 'https://www.engelvoelkers.com',
    industry: ['real-estate'],
    styleTags: ['luxurious', 'corporate', 'elegant'],
    colorSamples: ['#FFFFFF', '#E4002B', '#1A1A1A', '#F5F5F5', '#666666'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'features',
      'about',
      'team',
      'contact',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'International luxury real estate with a clean red-and-white European brand identity. Property grid with consistent card design across global markets.',
    displayOrder: 87,
  },
  {
    name: 'Triplemint',
    url: 'https://www.triplemint.com',
    industry: ['real-estate'],
    styleTags: ['modern', 'minimalist', 'tech'],
    colorSamples: ['#FFFFFF', '#3B5998', '#00C9A7', '#F7F8FC', '#333333'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Tech-forward NYC brokerage with a blue-teal palette. Data-driven approach with market insights, savings calculators, and a streamlined search interface.',
    displayOrder: 88,
  },
  {
    name: 'Knight Frank',
    url: 'https://www.knightfrank.com',
    industry: ['real-estate'],
    styleTags: ['corporate', 'elegant', 'modern'],
    colorSamples: ['#FFFFFF', '#002855', '#96774A', '#F0F0F0', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'features',
      'stats',
      'about',
      'contact',
      'footer',
    ],
    typography: 'serif',
    layoutStyle: 'two-column',
    description:
      'Global property consultancy with a traditional navy-gold palette and two-column content layout. Serif type and market research data reinforce authority.',
    displayOrder: 89,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // EDUCATION (90-99)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Coursera',
    url: 'https://www.coursera.org',
    industry: ['education'],
    styleTags: ['modern', 'bold', 'corporate'],
    colorSamples: ['#FFFFFF', '#0056D2', '#1F1F1F', '#F5F5F5', '#2A73CC'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'gallery',
      'testimonials',
      'stats',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Leading online learning platform with a bold blue identity. Course catalog grid with category filters, ratings, and university logos create a trusted marketplace.',
    displayOrder: 90,
  },
  {
    name: 'Masterclass',
    url: 'https://www.masterclass.com',
    industry: ['education'],
    styleTags: ['dark-mode', 'luxurious', 'elegant'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#C8A96E', '#1A1A1A', '#888888'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'features',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Celebrity-taught online classes with a cinematic dark-mode design. Gold accents, dramatic instructor portraits, and trailer-style video heroes set a premium tone.',
    displayOrder: 91,
  },
  {
    name: 'Duolingo',
    url: 'https://www.duolingo.com',
    industry: ['education'],
    styleTags: ['playful', 'bold', 'modern'],
    colorSamples: ['#58CC02', '#FFFFFF', '#1CB0F6', '#FFC800', '#FF4B4B'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Language learning app with a signature bright green and multi-color character palette. Playful mascot-driven design with gamification elements throughout.',
    displayOrder: 92,
  },
  {
    name: 'Khan Academy',
    url: 'https://www.khanacademy.org',
    industry: ['education'],
    styleTags: ['modern', 'organic', 'playful'],
    colorSamples: ['#FFFFFF', '#14BF96', '#1B262C', '#F5F5F5', '#4A4A4A'],
    sectionTypes: ['navigation', 'hero', 'features', 'stats', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Free education platform with a calming teal-green palette and friendly illustrations. Warm, inclusive design makes learning accessible and non-intimidating.',
    displayOrder: 93,
  },
  {
    name: 'Brilliant',
    url: 'https://brilliant.org',
    industry: ['education'],
    styleTags: ['dark-mode', 'modern', 'bold'],
    colorSamples: ['#1E1E2E', '#FFFFFF', '#FFB800', '#2D2D44', '#888888'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Interactive STEM learning with a dark academic aesthetic and gold accents. Mathematical visualizations and interactive puzzles demonstrate the product inline.',
    displayOrder: 94,
  },
  {
    name: 'Skillshare',
    url: 'https://www.skillshare.com',
    industry: ['education'],
    styleTags: ['modern', 'bold', 'gradient'],
    colorSamples: ['#FFFFFF', '#002333', '#00FF84', '#F5F5F5', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'features',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Creative skills marketplace with a dark green brand and bright green accent. Grid-based class thumbnails with instructor faces and time estimates.',
    displayOrder: 95,
  },
  {
    name: 'Udemy',
    url: 'https://www.udemy.com',
    industry: ['education'],
    styleTags: ['modern', 'corporate', 'bold'],
    colorSamples: ['#FFFFFF', '#5624D0', '#1C1D1F', '#F7F9FA', '#EC5252'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'features',
      'stats',
      'testimonials',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Massive online course marketplace with purple brand identity. Dense grid layout with ratings, price badges, and category carousels optimized for discovery.',
    displayOrder: 96,
  },
  {
    name: 'Notion Academy',
    url: 'https://www.notion.so/product/docs',
    industry: ['education', 'saas'],
    styleTags: ['minimalist', 'playful', 'modern'],
    colorSamples: ['#FFFFFF', '#37352F', '#E16259', '#F7F6F3', '#9B9A97'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Knowledge management education hub with Notion warm cream aesthetic. Inline interactive examples and hand-drawn illustrations teach by showing, not telling.',
    displayOrder: 97,
  },
  {
    name: 'Lambda School',
    url: 'https://www.bloomtech.com',
    industry: ['education'],
    styleTags: ['modern', 'tech', 'bold'],
    colorSamples: ['#FFFFFF', '#1A0B2E', '#FF3366', '#F5F5F5', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Tech bootcamp with a deep purple-and-pink palette. Outcome-driven stats, salary increase data, and employer logos build credibility for career changers.',
    displayOrder: 98,
  },
  {
    name: 'Maven',
    url: 'https://maven.com',
    industry: ['education'],
    styleTags: ['modern', 'elegant', 'minimalist'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#6366F1', '#F8F9FA', '#666666'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'features',
      'testimonials',
      'stats',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Cohort-based course platform with a refined indigo accent and clean typography. Instructor-led class cards with live session scheduling create urgency.',
    displayOrder: 99,
  },
]
