export interface WebsiteInspirationSeedData {
  name: string
  url: string
  industry: string[]
  styleTags: string[]
  colorSamples: string[]
  sectionTypes: string[]
  typography: string | null
  layoutStyle: string | null
  description: string
  displayOrder: number
}

export const WEBSITE_INSPIRATIONS_DATA: WebsiteInspirationSeedData[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // AGENCY / STUDIO (0-9) — sourced from siteinspire.com
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Collins',
    url: 'https://www.wearecollins.com',
    industry: ['agency'],
    styleTags: ['bold', 'typographic', 'editorial'],
    colorSamples: ['#000000', '#FFFFFF', '#FF4500', '#F5F5F0'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Bold brand consultancy with oversized typography and a striking editorial grid. High-contrast black and white with bursts of color.',
    displayOrder: 0,
  },
  {
    name: 'Norgram',
    url: 'https://www.norgram.co',
    industry: ['agency'],
    styleTags: ['minimalist', 'clean', 'modern'],
    colorSamples: ['#1A1A1A', '#FFFFFF', '#E8E8E8', '#0066FF'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Scandinavian design studio with a refined minimal aesthetic. Generous white space, subtle animations, and careful typographic hierarchy.',
    displayOrder: 1,
  },
  {
    name: 'Melody Digital',
    url: 'https://melodydigital.co',
    industry: ['agency'],
    styleTags: ['animated', 'modern', 'dark-mode'],
    colorSamples: ['#0D0D0D', '#FFFFFF', '#7B61FF', '#00D4AA'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Creative digital agency with smooth scroll-driven animations, a dark palette, and vibrant accent colors that feel alive.',
    displayOrder: 2,
  },
  {
    name: 'Ars Thanea',
    url: 'https://arsthanea.com',
    industry: ['agency'],
    styleTags: ['dark-mode', 'cinematic', 'animated'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#FF3366', '#1A1A2E'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'team', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Visual effects and CGI studio with cinematic full-screen imagery, dark backgrounds, and immersive hover interactions.',
    displayOrder: 3,
  },
  {
    name: 'Offsite',
    url: 'https://www.off.site',
    industry: ['agency'],
    styleTags: ['minimalist', 'elegant', 'typographic'],
    colorSamples: ['#FAFAF8', '#1A1A1A', '#C8B89A', '#E8E4DE'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Refined retreat-focused brand with warm neutral tones, elegant serif typography, and a sense of calm throughout.',
    displayOrder: 4,
  },
  {
    name: 'Groth Studio',
    url: 'https://www.groth.studio',
    industry: ['agency'],
    styleTags: ['minimalist', 'clean', 'geometric'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#F0F0F0', '#333333'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Danish design studio with clean geometric layouts, restrained color palette, and precise grid-based compositions.',
    displayOrder: 5,
  },
  {
    name: 'Making Software',
    url: 'https://www.makingsoftware.com',
    industry: ['agency'],
    styleTags: ['modern', 'clean', 'typographic'],
    colorSamples: ['#FFFFFF', '#000000', '#0055FF', '#F5F5F5'],
    sectionTypes: ['navigation', 'hero', 'features', 'about', 'gallery', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Software consultancy with clear information hierarchy, strong typography, and a professional yet approachable tone.',
    displayOrder: 6,
  },
  {
    name: 'Special Offer',
    url: 'https://s-o.io',
    industry: ['agency'],
    styleTags: ['minimalist', 'bold', 'typographic'],
    colorSamples: ['#FFFFFF', '#000000', '#FF0000', '#EEEEEE'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Provocative agency site with bold type, stark contrast, and a deliberately stripped-back approach to layout.',
    displayOrder: 7,
  },
  {
    name: 'Early Works',
    url: 'https://www.early.works',
    industry: ['agency'],
    styleTags: ['minimalist', 'elegant', 'modern'],
    colorSamples: ['#FAF9F6', '#1A1A1A', '#D4C5A9', '#E8E4DE'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Design practice with refined restraint—warm off-whites, thoughtful serif typography, and an editorial sensibility.',
    displayOrder: 8,
  },
  {
    name: 'Autograph',
    url: 'https://autograph.works',
    industry: ['agency'],
    styleTags: ['typographic', 'minimalist', 'clean'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#888888', '#F0F0F0'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'cta', 'footer'],
    typography: 'mixed',
    layoutStyle: 'full-width',
    description:
      'Brand design studio with sophisticated type pairing, clean layouts, and a quiet confidence in their work showcase.',
    displayOrder: 9,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SAAS / TECHNOLOGY (10-19)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Microsoft AI',
    url: 'https://microsoft.ai',
    industry: ['saas'],
    styleTags: ['modern', 'colorful', 'animated'],
    colorSamples: ['#FFFFFF', '#0078D4', '#50E6FF', '#1A1A1A'],
    sectionTypes: ['navigation', 'hero', 'features', 'about', 'gallery', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Microsoft AI platform with fluid gradient animations, clear product storytelling, and a polished enterprise aesthetic.',
    displayOrder: 10,
  },
  {
    name: 'Wabi',
    url: 'https://wabi.ai',
    industry: ['saas'],
    styleTags: ['minimalist', 'elegant', 'modern'],
    colorSamples: ['#FEFDF8', '#1A1A1A', '#E8DFD0', '#8B7355'],
    sectionTypes: ['navigation', 'hero', 'features', 'about', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'AI product with a warm, almost boutique-like aesthetic. Soft cream backgrounds and thoughtful micro-interactions.',
    displayOrder: 11,
  },
  {
    name: 'Legora',
    url: 'https://legora.com',
    industry: ['saas'],
    styleTags: ['clean', 'modern', 'corporate'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#4A90D9', '#F5F7FA'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Legal tech platform with a clean, trustworthy design. Blue accents convey reliability while modern layout feels accessible.',
    displayOrder: 12,
  },
  {
    name: 'Vast',
    url: 'https://www.vastspace.com',
    industry: ['saas'],
    styleTags: ['dark-mode', 'cinematic', 'bold'],
    colorSamples: ['#0A0A14', '#FFFFFF', '#4488FF', '#1A1A2E'],
    sectionTypes: ['navigation', 'hero', 'features', 'about', 'gallery', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Space station company with a dramatic dark palette, cinematic imagery, and bold typography that conveys scale and ambition.',
    displayOrder: 13,
  },
  {
    name: 'Mobbin',
    url: 'https://mobbin.com',
    industry: ['saas'],
    styleTags: ['clean', 'modern', 'colorful'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#6366F1', '#F3F4F6'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'gallery',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Design reference library with a polished product-led layout. Clean cards, vibrant purple accents, and excellent information density.',
    displayOrder: 14,
  },
  {
    name: 'Openfield',
    url: 'https://of.domains',
    industry: ['saas'],
    styleTags: ['minimalist', 'typographic', 'modern'],
    colorSamples: ['#FFFFFF', '#000000', '#E0E0E0', '#1A1A1A'],
    sectionTypes: ['navigation', 'hero', 'features', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Domain platform with ultra-minimal design. Typography-first approach with maximum breathing room and sharp interactions.',
    displayOrder: 15,
  },
  {
    name: 'Cycle',
    url: 'https://www.cycle-platform.tech',
    industry: ['saas'],
    styleTags: ['modern', 'colorful', 'animated'],
    colorSamples: ['#0F0F23', '#FFFFFF', '#7B61FF', '#00D4AA'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'about',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Product feedback platform with a gradient-rich dark aesthetic, smooth animations, and excellent feature showcasing.',
    displayOrder: 16,
  },
  {
    name: 'Linear',
    url: 'https://linear.app',
    industry: ['saas'],
    styleTags: ['dark-mode', 'minimalist', 'modern'],
    colorSamples: ['#0A0A0F', '#FFFFFF', '#5E6AD2', '#1A1A2E'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Project management tool with an iconic dark interface, refined purple accents, and buttery smooth scroll animations.',
    displayOrder: 17,
  },
  {
    name: 'Vercel',
    url: 'https://vercel.com',
    industry: ['saas'],
    styleTags: ['dark-mode', 'modern', 'animated'],
    colorSamples: ['#000000', '#FFFFFF', '#0070F3', '#333333'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'gallery',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Developer platform with a signature black aesthetic, gradient effects, and world-class motion design on scroll.',
    displayOrder: 18,
  },
  {
    name: 'Resend',
    url: 'https://resend.com',
    industry: ['saas'],
    styleTags: ['dark-mode', 'clean', 'modern'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#00D4AA', '#1A1A2E'],
    sectionTypes: ['navigation', 'hero', 'features', 'about', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Email API with a developer-focused dark design, clean code examples, and a polished product-led growth layout.',
    displayOrder: 19,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // E-COMMERCE / RETAIL (20-29)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Zia Tile',
    url: 'https://ziatile.com',
    industry: ['ecommerce'],
    styleTags: ['elegant', 'modern', 'colorful'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#C8956B', '#F5F0EB'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Artisan tile company with rich product photography, warm earth tones, and an immersive grid-based product showcase.',
    displayOrder: 20,
  },
  {
    name: 'MADH',
    url: 'https://www.madhstore.com',
    industry: ['ecommerce'],
    styleTags: ['bold', 'modern', 'editorial'],
    colorSamples: ['#FFFFFF', '#000000', '#FF4500', '#F5F5F5'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Contemporary retail with bold editorial layouts, oversized product shots, and a confident use of negative space.',
    displayOrder: 21,
  },
  {
    name: 'Palmer',
    url: 'https://www.palmer-dinnerware.com',
    industry: ['ecommerce'],
    styleTags: ['elegant', 'minimalist', 'organic'],
    colorSamples: ['#FAF8F3', '#2C2C2C', '#D4B896', '#E8E0D4'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'features', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Dinnerware brand with an organic, tactile feel. Warm cream backgrounds, serif typography, and lifestyle photography.',
    displayOrder: 22,
  },
  {
    name: 'No Fear',
    url: 'https://www.nofear.com',
    industry: ['ecommerce'],
    styleTags: ['bold', 'dark-mode', 'animated'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#FF0000', '#333333'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Streetwear revival with aggressive dark visuals, bold red accents, and high-energy animations that match the brand attitude.',
    displayOrder: 23,
  },
  {
    name: 'Akke Knitwear',
    url: 'https://akkeknitwear.com',
    industry: ['ecommerce'],
    styleTags: ['minimalist', 'organic', 'elegant'],
    colorSamples: ['#F8F6F1', '#2C2C2C', '#B8A88A', '#E8E0D4'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Artisan knitwear with soft, textured photography and a natural palette. The design mirrors the handmade quality of the products.',
    displayOrder: 24,
  },
  {
    name: '23 Gradi Coffee',
    url: 'https://www.23gradicoffee.com',
    industry: ['ecommerce', 'food-beverage'],
    styleTags: ['elegant', 'typographic', 'modern'],
    colorSamples: ['#1A1206', '#F5E6C8', '#8B6914', '#FFFFFF'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'features', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Italian coffee brand with luxurious dark roast tones, gold accents, and elegant serif typography that evokes coffee culture.',
    displayOrder: 25,
  },
  {
    name: 'CREGG Paris',
    url: 'https://www.cregg-paris.com',
    industry: ['ecommerce', 'fashion'],
    styleTags: ['elegant', 'minimalist', 'luxury'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#C8B89A', '#F5F3EF'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Parisian accessories brand with luxurious restraint. Cream and gold palette, serif type, and large-scale product imagery.',
    displayOrder: 26,
  },
  {
    name: 'Aesop',
    url: 'https://www.aesop.com',
    industry: ['ecommerce'],
    styleTags: ['elegant', 'minimalist', 'organic'],
    colorSamples: ['#F6F1EB', '#1A1A1A', '#9B8B6E', '#E8DFD0'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'footer'],
    typography: 'serif',
    layoutStyle: 'grid',
    description:
      'Skincare brand with signature warm earth tones, beautiful product photography, and a tactile, almost print-like digital experience.',
    displayOrder: 27,
  },
  {
    name: 'Mejuri',
    url: 'https://mejuri.com',
    industry: ['ecommerce'],
    styleTags: ['modern', 'clean', 'elegant'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#D4AF37', '#F5F5F0'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Fine jewelry brand with a modern, accessible luxury feel. Gold accents, clean product cards, and aspirational lifestyle imagery.',
    displayOrder: 28,
  },
  {
    name: 'Allbirds',
    url: 'https://www.allbirds.com',
    industry: ['ecommerce'],
    styleTags: ['colorful', 'playful', 'modern'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#2D6A4F', '#F4845F'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'gallery',
      'about',
      'testimonials',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Sustainable footwear with a playful, nature-inspired palette. Rounded shapes, friendly typography, and eco-messaging woven throughout.',
    displayOrder: 29,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // FASHION / LUXURY (30-37)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'JW Anderson',
    url: 'https://jwanderson.com',
    industry: ['fashion'],
    styleTags: ['editorial', 'bold', 'modern'],
    colorSamples: ['#FFFFFF', '#000000', '#E8E8E8', '#1A1A1A'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Fashion house with editorial-grade photography, bold grid layouts, and a stark black-and-white palette that lets garments speak.',
    displayOrder: 30,
  },
  {
    name: 'Veil Obscura',
    url: 'https://veilobscura.com.au',
    industry: ['fashion'],
    styleTags: ['dark-mode', 'editorial', 'elegant'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#8B7355', '#1A1A1A'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Dark, atmospheric fashion brand with moody editorial photography, serif type, and a sense of mystery throughout.',
    displayOrder: 31,
  },
  {
    name: 'Mason & Fifth',
    url: 'https://mason-fifth.com',
    industry: ['fashion'],
    styleTags: ['minimalist', 'elegant', 'organic'],
    colorSamples: ['#F8F6F0', '#2C2C2C', '#C8B89A', '#E8E0D4'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'Artisan fashion with understated luxury. Warm neutral tones, organic textures, and a quiet confidence in the design.',
    displayOrder: 32,
  },
  {
    name: 'Glossier',
    url: 'https://www.glossier.com',
    industry: ['fashion', 'ecommerce'],
    styleTags: ['playful', 'modern', 'colorful'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#F5C6D0', '#D4E7C5'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Beauty brand that defined a generation of DTC design. Millennial pink, friendly rounded type, and community-driven layout.',
    displayOrder: 33,
  },
  {
    name: 'Everlane',
    url: 'https://www.everlane.com',
    industry: ['fashion', 'ecommerce'],
    styleTags: ['clean', 'modern', 'minimalist'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#F5F5F0', '#4A4A4A'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Transparent pricing fashion brand with clean product grids, editorial photography, and a no-nonsense design language.',
    displayOrder: 34,
  },
  {
    name: 'Gymshark',
    url: 'https://www.gymshark.com',
    industry: ['fashion', 'ecommerce'],
    styleTags: ['bold', 'dark-mode', 'animated'],
    colorSamples: ['#1A1A1A', '#FFFFFF', '#00D4AA', '#333333'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Activewear brand with high-energy dark design, bold CTAs, athlete photography, and scroll-driven product reveals.',
    displayOrder: 35,
  },
  {
    name: 'Away',
    url: 'https://www.awaytravel.com',
    industry: ['fashion', 'ecommerce'],
    styleTags: ['modern', 'colorful', 'clean'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#4169E1', '#F5F0E8'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Luggage brand with vibrant color-blocked sections, aspirational travel imagery, and a clean product showcase.',
    displayOrder: 36,
  },
  {
    name: 'Casper',
    url: 'https://casper.com',
    industry: ['ecommerce'],
    styleTags: ['playful', 'clean', 'modern'],
    colorSamples: ['#FFFFFF', '#1A2B49', '#7BB8E1', '#F5E6D8'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'pricing',
      'faq',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Sleep brand with friendly blue palette, illustrated elements, clear pricing comparison, and trust-building social proof.',
    displayOrder: 37,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PORTFOLIO / PERSONAL (38-45)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Jon Howell',
    url: 'https://www.jonhowell.com',
    industry: ['portfolio'],
    styleTags: ['minimalist', 'typographic', 'clean'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#888888', '#F5F5F5'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Designer portfolio with impeccable typography, generous spacing, and a curated showcase that lets the work breathe.',
    displayOrder: 38,
  },
  {
    name: 'Stephanie Thatenhorst',
    url: 'https://stephanie-thatenhorst.com',
    industry: ['portfolio', 'architecture'],
    styleTags: ['elegant', 'editorial', 'organic'],
    colorSamples: ['#F5F0E8', '#2C2C2C', '#C8B89A', '#FFFFFF'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Interior designer portfolio with warm editorial photography, organic textures, and serif typography conveying refined taste.',
    displayOrder: 39,
  },
  {
    name: 'Garriock & Co.',
    url: 'https://garriock.com',
    industry: ['portfolio', 'agency'],
    styleTags: ['minimalist', 'modern', 'typographic'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#555555', '#F0F0F0'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Design portfolio with clean grid system, careful type sizing, and a focused presentation of project case studies.',
    displayOrder: 40,
  },
  {
    name: 'Brittany Chiang',
    url: 'https://brittanychiang.com',
    industry: ['portfolio'],
    styleTags: ['dark-mode', 'modern', 'animated'],
    colorSamples: ['#0A192F', '#CCD6F6', '#64FFDA', '#233554'],
    sectionTypes: ['navigation', 'hero', 'about', 'features', 'gallery', 'contact', 'footer'],
    typography: 'mono',
    layoutStyle: 'single-column',
    description:
      'Developer portfolio with a signature navy-and-teal palette, monospace typography, and smooth section transitions.',
    displayOrder: 41,
  },
  {
    name: 'Paco Coursey',
    url: 'https://paco.me',
    industry: ['portfolio'],
    styleTags: ['minimalist', 'dark-mode', 'typographic'],
    colorSamples: ['#111111', '#EEEEEE', '#888888', '#1A1A1A'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Developer portfolio with extreme minimalism. Dark background, subtle gray type, and a focus on writing and projects.',
    displayOrder: 42,
  },
  {
    name: 'Rauno Freiberg',
    url: 'https://rauno.me',
    industry: ['portfolio'],
    styleTags: ['minimalist', 'dark-mode', 'animated'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#888888', '#1A1A1A'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Vercel designer portfolio with craft-focused micro-interactions, dark minimal aesthetic, and attention to motion detail.',
    displayOrder: 43,
  },
  {
    name: 'Dennis Snellenberg',
    url: 'https://dennissnellenberg.com',
    industry: ['portfolio'],
    styleTags: ['bold', 'animated', 'dark-mode'],
    colorSamples: ['#0F0F0F', '#FFFFFF', '#FF4500', '#1A1A1A'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Award-winning developer portfolio with bold scroll-driven animations, magnetic cursor effects, and immersive transitions.',
    displayOrder: 44,
  },
  {
    name: 'Lapa Ninja',
    url: 'https://www.lapa.ninja',
    industry: ['portfolio', 'saas'],
    styleTags: ['clean', 'modern', 'colorful'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#6366F1', '#F3F4F6'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Landing page gallery with a clean card-based grid, category filters, and a practical design that serves its reference purpose.',
    displayOrder: 45,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // FOOD & BEVERAGE (46-51)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Indoek',
    url: 'https://indoek.com',
    industry: ['food-beverage', 'culture'],
    styleTags: ['organic', 'editorial', 'modern'],
    colorSamples: ['#F8F5F0', '#2C2C2C', '#8B9B7A', '#E8E0D4'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'features', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Surf and lifestyle brand with organic photography, earthy green tones, and an editorial approach to storytelling.',
    displayOrder: 46,
  },
  {
    name: 'Blue Bottle Coffee',
    url: 'https://bluebottlecoffee.com',
    industry: ['food-beverage', 'ecommerce'],
    styleTags: ['minimalist', 'clean', 'elegant'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#4A90D9', '#F5F5F0'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'features', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'single-column',
    description:
      'Specialty coffee brand with trademark blue, clean product photography, and a focused single-column narrative layout.',
    displayOrder: 47,
  },
  {
    name: 'Sweetgreen',
    url: 'https://www.sweetgreen.com',
    industry: ['food-beverage'],
    styleTags: ['colorful', 'playful', 'modern'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#4CAF50', '#F5E6D8'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Fast-casual salad chain with vibrant food photography, fresh green palette, and an approachable, health-forward design.',
    displayOrder: 48,
  },
  {
    name: 'Shake Shack',
    url: 'https://www.shakeshack.com',
    industry: ['food-beverage'],
    styleTags: ['bold', 'modern', 'playful'],
    colorSamples: ['#1D1D1D', '#FFFFFF', '#76B82A', '#F5F0E8'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Burger chain with signature green, mouth-watering food photography, and a bold, energetic brand presence online.',
    displayOrder: 49,
  },
  {
    name: 'Noma',
    url: 'https://noma.dk',
    industry: ['food-beverage'],
    styleTags: ['elegant', 'editorial', 'minimalist'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#8B7355', '#F5F0E8'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'single-column',
    description:
      'World-renowned restaurant with understated elegance. Beautiful food photography, serif typography, and quiet sophistication.',
    displayOrder: 50,
  },
  {
    name: 'Dishoom',
    url: 'https://www.dishoom.com',
    industry: ['food-beverage'],
    styleTags: ['retro', 'elegant', 'typographic'],
    colorSamples: ['#1A1206', '#F5E6C8', '#8B6914', '#FFFFFF'],
    sectionTypes: ['navigation', 'hero', 'about', 'gallery', 'features', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Bombay-inspired restaurant with nostalgic sepia tones, ornate typography, and a rich narrative that transports visitors.',
    displayOrder: 51,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // CULTURE / MEDIA / EDUCATION (52-57)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Emergence Magazine',
    url: 'https://emergencemagazine.org',
    industry: ['culture'],
    styleTags: ['editorial', 'elegant', 'organic'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#6B8E5E', '#F5F0E8'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Environmental magazine with immersive long-form storytelling, nature photography, and an editorial serif design language.',
    displayOrder: 52,
  },
  {
    name: 'Barcelona Arts Summer School',
    url: 'https://bassbcn.com',
    industry: ['culture', 'education'],
    styleTags: ['bold', 'colorful', 'geometric'],
    colorSamples: ['#FFFFFF', '#FF3366', '#FFD700', '#0055FF'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'about', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Art school with vibrant primary colors, bold geometric shapes, and an energetic layout that captures creative education.',
    displayOrder: 53,
  },
  {
    name: 'Virgil Abloh Archive',
    url: 'https://virgilabloh.com',
    industry: ['culture', 'fashion'],
    styleTags: ['editorial', 'bold', 'typographic'],
    colorSamples: ['#FFFFFF', '#000000', '#FF4500', '#E8E8E8'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Archive of the late designer with a powerful editorial grid, stark black-and-white, and moments of color that honor the work.',
    displayOrder: 54,
  },
  {
    name: 'Masterclass',
    url: 'https://www.masterclass.com',
    industry: ['education'],
    styleTags: ['dark-mode', 'cinematic', 'elegant'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#C8A96E', '#1A1A1A'],
    sectionTypes: [
      'navigation',
      'hero',
      'gallery',
      'features',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Online education platform with cinematic instructor photography, gold accents on black, and premium storytelling.',
    displayOrder: 55,
  },
  {
    name: 'Brilliant',
    url: 'https://brilliant.org',
    industry: ['education', 'saas'],
    styleTags: ['colorful', 'playful', 'modern'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#FF6F61', '#4A90D9'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'STEM learning platform with interactive animations, vibrant colors, and clear visual explanations that make learning inviting.',
    displayOrder: 56,
  },
  {
    name: 'Duolingo',
    url: 'https://www.duolingo.com',
    industry: ['education', 'saas'],
    styleTags: ['playful', 'colorful', 'bold'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#58CC02', '#FF4B4B'],
    sectionTypes: ['navigation', 'hero', 'features', 'about', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Language learning app with signature green, playful character illustrations, and gamification cues throughout the design.',
    displayOrder: 57,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // ARCHITECTURE / INTERIOR (58-63)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Displaay',
    url: 'https://displaay.net',
    industry: ['architecture', 'agency'],
    styleTags: ['minimalist', 'typographic', 'geometric'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#888888', '#F0F0F0'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Type foundry with exquisite typographic specimens, clean grid layouts, and a design that showcases letterforms as art.',
    displayOrder: 58,
  },
  {
    name: 'New Apology',
    url: 'https://newapology.com',
    industry: ['architecture'],
    styleTags: ['minimalist', 'elegant', 'editorial'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#C8B89A', '#F5F0E8'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'contact', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Architecture studio with refined project presentations, elegant serif typography, and generous use of white space.',
    displayOrder: 59,
  },
  {
    name: 'Compass',
    url: 'https://www.compass.com',
    industry: ['real-estate'],
    styleTags: ['clean', 'modern', 'elegant'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#0A2540', '#F5F5F0'],
    sectionTypes: ['navigation', 'hero', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Real estate platform with clean property cards, elegant navy palette, and a premium browsing experience.',
    displayOrder: 60,
  },
  {
    name: 'Sothebys Realty',
    url: 'https://www.sothebysrealty.com',
    industry: ['real-estate'],
    styleTags: ['luxury', 'elegant', 'editorial'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#0A2540', '#D4AF37'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'features', 'about', 'cta', 'footer'],
    typography: 'serif',
    layoutStyle: 'full-width',
    description:
      'Luxury real estate with full-bleed property photography, gold accents, serif typography, and a premium editorial feel.',
    displayOrder: 61,
  },
  {
    name: 'Opendoor',
    url: 'https://www.opendoor.com',
    industry: ['real-estate', 'saas'],
    styleTags: ['modern', 'clean', 'colorful'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#6366F1', '#F3F4F6'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'faq', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Real estate tech with friendly, approachable design, clear value propositions, and trust-building social proof sections.',
    displayOrder: 62,
  },
  {
    name: 'Pentagram',
    url: 'https://www.pentagram.com',
    industry: ['architecture', 'agency'],
    styleTags: ['minimalist', 'editorial', 'typographic'],
    colorSamples: ['#FFFFFF', '#000000', '#E8E8E8', '#1A1A1A'],
    sectionTypes: ['navigation', 'hero', 'gallery', 'about', 'team', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'grid',
    description:
      'Legendary design consultancy with a project-first grid layout, stark black-and-white palette, and no-frills navigation.',
    displayOrder: 63,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // FINANCE / FINTECH (64-69)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Mercury',
    url: 'https://mercury.com',
    industry: ['finance'],
    styleTags: ['dark-mode', 'modern', 'clean'],
    colorSamples: ['#0F0F23', '#FFFFFF', '#7B61FF', '#1A1A2E'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'pricing', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Startup banking with a polished dark interface, purple accents, and clear product benefit sections that build trust.',
    displayOrder: 64,
  },
  {
    name: 'Ramp',
    url: 'https://ramp.com',
    industry: ['finance', 'saas'],
    styleTags: ['modern', 'clean', 'bold'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#00875A', '#F5F5F0'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'testimonials',
      'stats',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Corporate card platform with crisp green accents, impressive stat callouts, and a confident, enterprise-ready design.',
    displayOrder: 65,
  },
  {
    name: 'Wise',
    url: 'https://wise.com',
    industry: ['finance'],
    styleTags: ['modern', 'colorful', 'clean'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#9FE870', '#163300'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'stats',
      'testimonials',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'International money transfer with signature lime green, clear pricing transparency, and trust signals throughout.',
    displayOrder: 66,
  },
  {
    name: 'Brex',
    url: 'https://www.brex.com',
    industry: ['finance', 'saas'],
    styleTags: ['modern', 'dark-mode', 'bold'],
    colorSamples: ['#0F0F23', '#FFFFFF', '#FF6B35', '#1A1A2E'],
    sectionTypes: ['navigation', 'hero', 'features', 'testimonials', 'stats', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Spend management platform with a dark, enterprise-grade aesthetic, orange accent pops, and impressive client logos.',
    displayOrder: 67,
  },
  {
    name: 'Robinhood',
    url: 'https://robinhood.com',
    industry: ['finance'],
    styleTags: ['modern', 'clean', 'colorful'],
    colorSamples: ['#FFFFFF', '#1A1A1A', '#00C805', '#F5F5F0'],
    sectionTypes: ['navigation', 'hero', 'features', 'about', 'testimonials', 'cta', 'footer'],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Trading platform with clean, friendly design. Green accents, clear feature sections, and an approachable tone for retail investors.',
    displayOrder: 68,
  },
  {
    name: 'Revolut',
    url: 'https://www.revolut.com',
    industry: ['finance'],
    styleTags: ['dark-mode', 'bold', 'animated'],
    colorSamples: ['#0A0A0A', '#FFFFFF', '#0075EB', '#1A1A2E'],
    sectionTypes: [
      'navigation',
      'hero',
      'features',
      'gallery',
      'stats',
      'pricing',
      'cta',
      'footer',
    ],
    typography: 'sans-serif',
    layoutStyle: 'full-width',
    description:
      'Digital banking with bold dark design, blue accents, animated product mockups, and a dense feature showcase.',
    displayOrder: 69,
  },
]
